// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamWorld.Data;

#nullable disable

namespace StreamWorld.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111015432_AjusteProducaoPtBr")]
    partial class AjusteProducaoPtBr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("StreamWorld.Models.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("StreamWorld.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("StreamWorld.Models.MensagemContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("StreamWorld.Models.Producao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GeneroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sinopse")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.ToTable("Productions");
                });

            modelBuilder.Entity("StreamWorld.Models.ProducaoArtista", b =>
                {
                    b.Property<int>("ProducaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProducaoId", "ArtistaId");

                    b.HasIndex("ArtistaId");

                    b.ToTable("ProductionArtists");
                });

            modelBuilder.Entity("StreamWorld.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("StreamWorld.Models.Producao", b =>
                {
                    b.HasOne("StreamWorld.Models.Genero", "Genero")
                        .WithMany("Producoes")
                        .HasForeignKey("GeneroId");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("StreamWorld.Models.ProducaoArtista", b =>
                {
                    b.HasOne("StreamWorld.Models.Artista", "Artista")
                        .WithMany("ProducaoArtistas")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamWorld.Models.Producao", "Producao")
                        .WithMany("ProducaoArtistas")
                        .HasForeignKey("ProducaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artista");

                    b.Navigation("Producao");
                });

            modelBuilder.Entity("StreamWorld.Models.Artista", b =>
                {
                    b.Navigation("ProducaoArtistas");
                });

            modelBuilder.Entity("StreamWorld.Models.Genero", b =>
                {
                    b.Navigation("Producoes");
                });

            modelBuilder.Entity("StreamWorld.Models.Producao", b =>
                {
                    b.Navigation("ProducaoArtistas");
                });
#pragma warning restore 612, 618
        }
    }
}
